from main import *

animals = {
        "Fox": Animal(
            name="Fox",
            species="Vulpes vulpes",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Wolf": Animal(
            name="Wolf",
            species="Canis lupus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Bear": Animal(
            name="Bear",
            species="Ursus arctos",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=False,
            speed=Rank.D,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Hare": Animal(
            name="Hare",
            species="Lepus europaeus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Roe Deer": Animal(
            name="Roe Deer",
            species="Capreolus capreolus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.D,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Deer": Animal(
            name="Deer",
            species="Cervus elaphus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Rabbit": Animal(
            name="Rabbit",
            species="Oryctolagus cuniculus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.D,
            size=Size.S,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Squirrel": Animal(
            name="Squirrel",
            species="Sciurus vulgaris",
            diet=Diet.HERBIVORE,
            intelligence=Rank.D,
            size=Size.S,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Mouse": Animal(
            name="Mouse",
            species="Mus musculus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.D,
            size=Size.XS,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Boar": Animal(
            name="Boar",
            species="Sus scrofa",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.A,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Lion": Animal(
            name="Lion",
            species="Panthera leo",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Tiger": Animal(
            name="Tiger",
            species="Panthera tigris",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Leopard": Animal(
            name="Leopard",
            species="Panthera pardus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Cheetah": Animal(
            name="Cheetah",
            species="Acinonyx jubatus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.S,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Zebra": Animal(
            name="Zebra",
            species="Equus quagga",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Gazelle": Animal(
            name="Gazelle",
            species="Eudorcas thomsonii",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Hippopotamus": Animal(
            name="Hippopotamus",
            species="Hippopotamus amphibius",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=False,
            speed=Rank.D,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Elephant": Animal(
            name="Elephant",
            species="Loxodonta africana",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=False,
            speed=Rank.D,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Rhinoceros": Animal(
            name="Rhinoceros",
            species="Ceratotherium simum",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=False,
            speed=Rank.D,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Giraffe": Animal(
            name="Giraffe",
            species="Giraffa camelopardalis",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.C,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Crocodile": Animal(
            name="Crocodile",
            species="Crocodylus niloticus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=False,
            speed=Rank.D,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Turtle": Animal(
            name="Turtle",
            species="Trachemys scripta elegans",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Tortoise": Animal(
            name="Tortoise",
            species="Aldabrachelys gigantea",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Snake": Animal(
            name="Snake",
            species="Natrix natrix",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Lizard": Animal(
            name="Lizard",
            species="Zootoca vivipara",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Axolotl": Animal(
            name="Axolotl",
            species="Ambystoma mexicanum",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.AQUATIC
        ),
        "Salamander": Animal(
            name="Salamander",
            species="Salamandra salamandra",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Frog": Animal(
            name="Frog",
            species="Rana temporaria",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Aye-Aye": Animal(
            name="Aye-Aye",
            species="Daubentonia madagascariensis",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Lemur": Animal(
            name="Lemur",
            species="Lemur catta",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Monkey": Animal(
            name="Monkey",
            species="Macaca mulatta",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Mouse Lemur": Animal(
            name="Mouse Lemur",
            species="Microcebus lehilahytsara",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Gorilla": Animal(
            name="Gorilla",
            species="Gorilla gorilla",
            diet=Diet.OMNIVORE,
            intelligence=Rank.S,
            size=Size.XL,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.S,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Chimpanzee": Animal(
            name="Chimpanzee",
            species="Pan troglodytes",
            diet=Diet.OMNIVORE,
            intelligence=Rank.S,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.S,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Bonobo": Animal(
            name="Bonobo",
            species="Pan paniscus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.S,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.S,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Orangutan": Animal(
            name="Orangutan",
            species="Pongo pygmaeus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.S,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Tit": Animal(
            name="Tit",
            species="Parus major",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Robin": Animal(
            name="Robin",
            species="Erithacus rubecula",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Woodpecker": Animal(
            name="Woodpecker",
            species="Dendrocopos major",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.S,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Pigeon": Animal(
            name="Pigeon",
            species="Columba livia",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.S,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Eagle": Animal(
            name="Eagle",
            species="Aquila chrysaetos",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Harpy": Animal(
            name="Harpy",
            species="Pithecopaga jefferyi",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Vulture": Animal(
            name="Vulture",
            species="Gyps fulvus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Owl": Animal(
            name="Owl",
            species="Bubo bubo",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Saola": Animal(
            name="Saola",
            species="Pseudoryx nghetinhensis",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Okapi": Animal(
            name="Okapi",
            species="Okapia johnstoni",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Koala": Animal(
            name="Koala",
            species="Phascolarctos cinereus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.F,
            size=Size.M,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Sloth": Animal(
            name="Sloth",
            species="Bradypus variegatus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.F,
            size=Size.S,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC # Sloths can swim quite well
        ),
        "Giant Panda": Animal(
            name="Giant Panda",
            species="Ailuropoda melanoleuca",
            diet=Diet.HERBIVORE,
            intelligence=Rank.C,
            size=Size.L,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Red Panda": Animal(
            name="Red Panda",
            species="Ailurus fulgens",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Raccoon": Animal(
            name="Raccoon", #Could be Trash Panda
            species="Procyon lotor",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Raccoon Dog": Animal(
            name="Raccoon Dog", #Trash Panda Dog lol
            species="Nyctereutes procyonoides",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Pangolin": Animal(
            name="Pangolin",
            species="Manis pentadactyla",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.M,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Armadillo": Animal(
            name="Armadillo",
            species="Dasypus novemcinctus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.M,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Anteater": Animal(
            name="Anteater",
            species="Myrmecophaga tridactyla",
            diet=Diet.OMNIVORE,
            intelligence=Rank.C,
            size=Size.L,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Megatherium": Animal(
            name="Megatherium",
            species="Megatherium americanum",
            diet=Diet.HERBIVORE,
            intelligence=Rank.C,
            size=Size.XL,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.A,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Mammoth": Animal(
            name="Mammoth",
            species="Mammuthus primigenius",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.XL,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Sabre-Toothed Tiger": Animal(
            name="Sabre-Toothed Tiger",
            species="Smilodon fatalis",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.S,
            weight=Rank.A,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Tyrannosaurus": Animal(
            name="Tyrannosaurus",
            species="Tyrannosaurus rex",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.XXL,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Velociraptor": Animal(
            name="Velociraptor",
            species="Velociraptor mongoliensis",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.S,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Dodo": Animal(
            name="Dodo",
            species="Raphus cucullatus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.F,
            size=Size.M,
            has_wings=True,
            speed=Rank.F,
            damage=Rank.F,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Penguin": Animal(
            name="Penguin",
            species="Aptenodytes forsteri",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=True,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC # Penguins are semi-aquatic birbs
        ),
        "Ostrich": Animal(
            name="Ostrich",
            species="Struthio camelus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.A,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Hatzegopteryx": Animal(
            name="Hatzegopteryx",
            species="Hatzegopteryx thambema",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.S,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Pteranodon": Animal(
            name="Pteranodon",
            species="Pteranodon longiceps",
            diet=Diet.CARNIVORE,
            intelligence=Rank.C,
            size=Size.L,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Salmon": Animal(
            name="Salmon",
            species="Oncorhynchus nerka",
            diet=Diet.CARNIVORE,
            intelligence=Rank.D,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.AQUATIC
        ),
        "Shark": Animal(
            name="Shark",
            species="Carcharodon carcharias",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.XL,
            has_wings=False,
            speed=Rank.S,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.AQUATIC
        ),
        "Sea Turtle": Animal(
            name="Sea Turtle",
            species="Chelonia mydas",
            diet=Diet.HERBIVORE,
            intelligence=Rank.C,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.AQUATIC
        ),
        "Sea Lion": Animal(
            name="Sea Lion",
            species="Zalophus californianus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Sea Otter": Animal(
            name="Sea Otter",
            species="Enhydra lutris",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Seal": Animal(
            name="Seal",
            species="Phoca vitulina",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Giant River Otter": Animal(
            name="Giant River Otter",
            species="Pteronura brasiliensis", # River Mafia lol
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Ibis": Animal(
            name="Ibis",
            species="Threskiornis aethiopicus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Stork": Animal(
            name="Stork",
            species="Ciconia ciconia",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Heron": Animal(
            name="Heron",
            species="Ardea cinerea",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Crane": Animal(
            name="Crane",
            species="Grus grus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Flamingo": Animal(
            name="Flamingo",
            species="Phoenicopterus roseus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Swan": Animal(
            name="Swan",
            species="Cygnus olor",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Goose": Animal(
            name="Goose",
            species="Branta canadensis",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Duck": Animal(
            name="Duck",
            species="Anas platyrhynchos",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Toucan": Animal(
            name="Toucan",
            species="Ramphastos toco",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.F,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Warthog": Animal(
            name="Warthog",
            species="Phacochoerus africanus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.B,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Meerkat": Animal(
            name="Meerkat",
            species="Suricata suricatta",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Hyena": Animal(
            name="Hyena",
            species="Crocuta crocuta",
            diet=Diet.CARNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Mandrill": Animal(
            name="Mandrill",
            species="Mandrillus sphinx",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Baboon": Animal(
            name="Baboon",
            species="Papio hamadryas",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Kangaroo": Animal(
            name="Kangaroo",
            species="Osphranter rufus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Echidna": Animal(
            name="Echidna",
            species="Tachyglossus aculeatus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Platypus": Animal(
            name="Platypus",
            species="Ornithorhynchus anatinus",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.C,
            damage=Rank.C,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Bullfinch": Animal(
            name="Bullfinch",
            species="Pyrrhula pyrrhula",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Quail": Animal(
            name="Quail",
            species="Coturnix coturnix",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Emu": Animal(
            name="Emu",
            species="Dromaius novaehollandiae",
            diet=Diet.OMNIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=True,
            speed=Rank.A,
            damage=Rank.A,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Colobus": Animal(
            name="Colobus",
            species="Colobus guereza",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Gelada": Animal(
            name="Gelada",
            species="Theropithecus gelada",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.B,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Proboscis Monkey": Animal(
            name="Proboscis Monkey",
            species="Nasalis larvatus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Snub-nosed Monkey": Animal(
            name="Snub-nosed Monkey",
            species="Rhinopithecus roxellana",
            diet=Diet.HERBIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Vervet": Animal(
            name="Vervet",
            species="Chlorocebus pygerythrus",
            diet=Diet.OMNIVORE,
            intelligence=Rank.A,
            size=Size.M,
            has_wings=False,
            speed=Rank.A,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=True,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Cormorant": Animal(
            name="Cormorant",
            species="Phalacrocorax carbo",
            diet=Diet.CARNIVORE,
            intelligence=Rank.B,
            size=Size.M,
            has_wings=True,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.C,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Quokka": Animal(
            name="Quokka",
            species="Setonix brachyurus",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.S,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.D,
            weight=Rank.D,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        ),
        "Capybara": Animal(
            name="Capybara",
            species="Hydrochoerus hydrochaeris",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.L,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.C,
            weight=Rank.B,
            has_arms=False,
            locomotion=Locomotion.SEMIAQUATIC
        ),
        "Diplodocus": Animal(
            name="Diplodocus",
            species="Diplodocus carnegii",
            diet=Diet.HERBIVORE,
            intelligence=Rank.B,
            size=Size.XXL,
            has_wings=False,
            speed=Rank.B,
            damage=Rank.S,
            weight=Rank.S,
            has_arms=False,
            locomotion=Locomotion.TERRESTRIAL
        )
    }